/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndoorRouteImport } from './routes/indoor'
import { Route as GpsRouteImport } from './routes/gps'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NavigateDestinationIdRouteImport } from './routes/navigate.$destinationId'
import { Route as NavigateRoomRoomIdRouteImport } from './routes/navigate-room.$roomId'

const IndoorRoute = IndoorRouteImport.update({
  id: '/indoor',
  path: '/indoor',
  getParentRoute: () => rootRouteImport,
} as any)
const GpsRoute = GpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateDestinationIdRoute = NavigateDestinationIdRouteImport.update({
  id: '/navigate/$destinationId',
  path: '/navigate/$destinationId',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateRoomRoomIdRoute = NavigateRoomRoomIdRouteImport.update({
  id: '/navigate-room/$roomId',
  path: '/navigate-room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/gps': typeof GpsRoute
  '/indoor': typeof IndoorRoute
  '/navigate-room/$roomId': typeof NavigateRoomRoomIdRoute
  '/navigate/$destinationId': typeof NavigateDestinationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/gps': typeof GpsRoute
  '/indoor': typeof IndoorRoute
  '/navigate-room/$roomId': typeof NavigateRoomRoomIdRoute
  '/navigate/$destinationId': typeof NavigateDestinationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/gps': typeof GpsRoute
  '/indoor': typeof IndoorRoute
  '/navigate-room/$roomId': typeof NavigateRoomRoomIdRoute
  '/navigate/$destinationId': typeof NavigateDestinationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/destinations'
    | '/gps'
    | '/indoor'
    | '/navigate-room/$roomId'
    | '/navigate/$destinationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/destinations'
    | '/gps'
    | '/indoor'
    | '/navigate-room/$roomId'
    | '/navigate/$destinationId'
  id:
    | '__root__'
    | '/'
    | '/destinations'
    | '/gps'
    | '/indoor'
    | '/navigate-room/$roomId'
    | '/navigate/$destinationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsRoute: typeof DestinationsRoute
  GpsRoute: typeof GpsRoute
  IndoorRoute: typeof IndoorRoute
  NavigateRoomRoomIdRoute: typeof NavigateRoomRoomIdRoute
  NavigateDestinationIdRoute: typeof NavigateDestinationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indoor': {
      id: '/indoor'
      path: '/indoor'
      fullPath: '/indoor'
      preLoaderRoute: typeof IndoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gps': {
      id: '/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof GpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate/$destinationId': {
      id: '/navigate/$destinationId'
      path: '/navigate/$destinationId'
      fullPath: '/navigate/$destinationId'
      preLoaderRoute: typeof NavigateDestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate-room/$roomId': {
      id: '/navigate-room/$roomId'
      path: '/navigate-room/$roomId'
      fullPath: '/navigate-room/$roomId'
      preLoaderRoute: typeof NavigateRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsRoute: DestinationsRoute,
  GpsRoute: GpsRoute,
  IndoorRoute: IndoorRoute,
  NavigateRoomRoomIdRoute: NavigateRoomRoomIdRoute,
  NavigateDestinationIdRoute: NavigateDestinationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
